# Calculate frequency of each alphabet on romaji texts

# You have to download https://github.com/ku-nlp/KWDLC in order to run this program.

# the constant kanamap is derived from https://github.com/jikyo/romaji4p/blob/master/romaji/mapping.py (Copyright 2018 Junnosuke Moriya)
# original code is licensed under Apache License 2.0
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

kanamap = {
    'あ': 'a',
    'い': 'i',
    'う': 'u',
    'え': 'e',
    'お': 'o',
    'うぁ': 'wha',
    'うぃ': 'whi',
    'うぇ': 'whe',
    'うぉ': 'who',
    'ゐ': 'wi',
    'ゑ': 'we',
    'ぁ': 'xa',
    'ぃ': 'xi',
    'ぅ': 'xu',
    'ぇ': 'xe',
    'ぉ': 'xo',
    'いぇ': 'ye',
    'か': 'ka',
    'き': 'ki',
    'く': 'ku',
    'け': 'ke',
    'こ': 'ko',
    'きゃ': 'kya',
    'きぃ': 'kyi',
    'きゅ': 'kyu',
    'きぇ': 'kye',
    'きょ': 'kyo',
    'くゃ': 'qya',
    'くゅ': 'qyu',
    'くょ': 'quo',
    'くぁ': 'qwa',
    'くぃ': 'qwi',
    'くぅ': 'qwu',
    'くぇ': 'qwe',
    'くぉ': 'qwo',
    'が': 'ga',
    'ぎ': 'gi',
    'ぐ': 'gu',
    'げ': 'ge',
    'ご': 'go',
    'ぎゃ': 'gya',
    'ぎぃ': 'gyi',
    'ぎゅ': 'gyu',
    'ぎぇ': 'gye',
    'ぎょ': 'gyo',
    'ぐぁ': 'gwa',
    'ぐぃ': 'gwi',
    'ぐぅ': 'gwu',
    'ぐぇ': 'gwe',
    'ぐぉ': 'gwo',
    'さ': 'sa',
    'し': 'si',
    'す': 'su',
    'せ': 'se',
    'そ': 'so',
    'しゃ': 'sya',
    'しぃ': 'syi',
    'しゅ': 'syu',
    'しぇ': 'sye',
    'しょ': 'syo',
    'すぁ': 'swa',
    'すぃ': 'swi',
    'すぅ': 'swu',
    'すぇ': 'swe',
    'すぉ': 'swo',
    'ざ': 'za',
    'じ': 'zi',
    'ず': 'zu',
    'ぜ': 'ze',
    'ぞ': 'zo',
    'じゃ': 'zya',
    'じぃ': 'zyi',
    'じゅ': 'zyu',
    'じぇ': 'zye',
    'じょ': 'zyo',
    'た': 'ta',
    'ち': 'ti',
    'つ': 'tu',
    'て': 'te',
    'と': 'to',
    'ちゃ': 'tya',
    'ちぃ': 'tyi',
    'ちゅ': 'tyu',
    'ちぇ': 'tye',
    'ちょ': 'tyo',
    'つぁ': 'tsa',
    'つぃ': 'tsi',
    'つぇ': 'tse',
    'つぉ': 'tso',
    'てゃ': 'tha',
    'てぃ': 'thi',
    'てゅ': 'thu',
    'てぇ': 'the',
    'てょ': 'tho',
    'とぁ': 'twa',
    'とぃ': 'twi',
    'とぅ': 'twu',
    'とぇ': 'twe',
    'とぉ': 'two',
    'だ': 'da',
    'ぢ': 'di',
    'づ': 'du',
    'で': 'de',
    'ど': 'do',
    'ぢゃ': 'dya',
    'ぢぃ': 'dyi',
    'ぢゅ': 'dyu',
    'ぢぇ': 'dye',
    'ぢょ': 'dyo',
    'でゃ': 'dha',
    'でぃ': 'dhi',
    'でゅ': 'dhu',
    'でぇ': 'dhe',
    'でょ': 'dho',
    'どぁ': 'dwa',
    'どぃ': 'dwi',
    'どぅ': 'dwu',
    'どぇ': 'dwe',
    'どぉ': 'dwo',
    'っ': 'xtu',
    'な': 'na',
    'に': 'ni',
    'ぬ': 'nu',
    'ね': 'ne',
    'の': 'no',
    'にゃ': 'nya',
    'にぃ': 'nyi',
    'にゅ': 'nyu',
    'にぇ': 'nye',
    'にょ': 'nyo',
    'は': 'ha',
    'ひ': 'hi',
    'ふ': 'hu',
    'へ': 'he',
    'ほ': 'ho',
    'ひゃ': 'hya',
    'ひぃ': 'hyi',
    'ひゅ': 'hyu',
    'ひぇ': 'hye',
    'ひょ': 'hyo',
    'ふぁ': 'fwa',
    'ふぃ': 'fwi',
    'ふぅ': 'fwu',
    'ふぇ': 'fwe',
    'ふぉ': 'fwo',
    'ふゃ': 'fya',
    'ふゅ': 'fyu',
    'ふょ': 'fyo',
    'ば': 'ba',
    'び': 'bi',
    'ぶ': 'bu',
    'べ': 'be',
    'ぼ': 'bo',
    'びゃ': 'bya',
    'びぃ': 'byi',
    'びゅ': 'byu',
    'びぇ': 'bye',
    'びょ': 'byo',
    'ぱ': 'pa',
    'ぴ': 'pi',
    'ぷ': 'pu',
    'ぺ': 'pe',
    'ぽ': 'po',
    'ぴゃ': 'pya',
    'ぴぃ': 'pyi',
    'ぴゅ': 'pyu',
    'ぴぇ': 'pye',
    'ぴょ': 'pyo',
    'ま': 'ma',
    'み': 'mi',
    'む': 'mu',
    'め': 'me',
    'も': 'mo',
    'みゃ': 'mya',
    'みぃ': 'myi',
    'みゅ': 'myu',
    'みぇ': 'mye',
    'みょ': 'myo',
    'や': 'ya',
    'ゆ': 'yu',
    'よ': 'yo',
    'ゃ': 'xya',
    'ゅ': 'xyu',
    'ょ': 'xyo',
    'ら': 'ra',
    'り': 'ri',
    'る': 'ru',
    'れ': 're',
    'ろ': 'ro',
    'りゃ': 'rya',
    'りぃ': 'ryi',
    'りゅ': 'ryu',
    'りぇ': 'rye',
    'りょ': 'ryo',
    'わ': 'wa',
    'を': 'wo',
    'ん': 'n',
    'ゎ': 'xwa',
    'ア': 'a',
    'イ': 'i',
    'ウ': 'u',
    'エ': 'e',
    'オ': 'o',
    'ウァ': 'wha',
    'ウィ': 'whi',
    'ウェ': 'whe',
    'ウォ': 'who',
    'ヰ': 'wi',
    'ヱ': 'we',
    'ァ': 'xa',
    'ィ': 'xi',
    'ゥ': 'xu',
    'ェ': 'xe',
    'ォ': 'xo',
    'イェ': 'ye',
    'カ': 'ka',
    'キ': 'ki',
    'ク': 'ku',
    'ケ': 'ke',
    'コ': 'ko',
    'キャ': 'kya',
    'キィ': 'kyi',
    'キュ': 'kyu',
    'キェ': 'kye',
    'キョ': 'kyo',
    'クャ': 'qya',
    'クュ': 'qyu',
    'クョ': 'quo',
    'クァ': 'qwa',
    'クィ': 'qwi',
    'クゥ': 'qwu',
    'クェ': 'qwe',
    'クォ': 'qwo',
    'ガ': 'ga',
    'ギ': 'gi',
    'グ': 'gu',
    'ゲ': 'ge',
    'ゴ': 'go',
    'ギャ': 'gya',
    'ギィ': 'gyi',
    'ギュ': 'gyu',
    'ギェ': 'gye',
    'ギョ': 'gyo',
    'グァ': 'gwa',
    'グィ': 'gwi',
    'グゥ': 'gwu',
    'グェ': 'gwe',
    'グォ': 'gwo',
    'ヵ': 'xka',
    'ヶ': 'xke',
    'サ': 'sa',
    'シ': 'si',
    'ス': 'su',
    'セ': 'se',
    'ソ': 'so',
    'シャ': 'sya',
    'シィ': 'syi',
    'シュ': 'syu',
    'シェ': 'sye',
    'ショ': 'syo',
    'スァ': 'swa',
    'スィ': 'swi',
    'スゥ': 'swu',
    'スェ': 'swe',
    'スォ': 'swo',
    'ザ': 'za',
    'ジ': 'zi',
    'ズ': 'zu',
    'ゼ': 'ze',
    'ゾ': 'zo',
    'ジャ': 'zya',
    'ジィ': 'zyi',
    'ジュ': 'zyu',
    'ジェ': 'zye',
    'ジョ': 'zyo',
    'タ': 'ta',
    'チ': 'ti',
    'ツ': 'tu',
    'テ': 'te',
    'ト': 'to',
    'チャ': 'tya',
    'チィ': 'tyi',
    'チュ': 'tyu',
    'チェ': 'tye',
    'チョ': 'tyo',
    'ツァ': 'tsa',
    'ツィ': 'tsi',
    'ツェ': 'tse',
    'ツォ': 'tso',
    'テャ': 'tha',
    'ティ': 'thi',
    'テュ': 'thu',
    'テェ': 'the',
    'テョ': 'tho',
    'トァ': 'twa',
    'トィ': 'twi',
    'トゥ': 'twu',
    'トェ': 'twe',
    'トォ': 'two',
    'ダ': 'da',
    'ヂ': 'di',
    'ヅ': 'du',
    'デ': 'de',
    'ド': 'do',
    'ヂャ': 'dya',
    'ヂィ': 'dyi',
    'ヂュ': 'dyu',
    'ヂェ': 'dye',
    'ヂョ': 'dyo',
    'デャ': 'dha',
    'ディ': 'dhi',
    'デュ': 'dhu',
    'デェ': 'dhe',
    'デョ': 'dho',
    'ドァ': 'dwa',
    'ドィ': 'dwi',
    'ドゥ': 'dwu',
    'ドェ': 'dwe',
    'ドォ': 'dwo',
    'ッ': 'xtu',
    'ナ': 'na',
    'ニ': 'ni',
    'ヌ': 'nu',
    'ネ': 'ne',
    'ノ': 'no',
    'ニャ': 'nya',
    'ニィ': 'nyi',
    'ニュ': 'nyu',
    'ニェ': 'nye',
    'ニョ': 'nyo',
    'ハ': 'ha',
    'ヒ': 'hi',
    'フ': 'hu',
    'ヘ': 'he',
    'ホ': 'ho',
    'ヒャ': 'hya',
    'ヒィ': 'hyi',
    'ヒュ': 'hyu',
    'ヒェ': 'hye',
    'ヒョ': 'hyo',
    'ファ': 'fwa',
    'フィ': 'fwi',
    'フゥ': 'fwu',
    'フェ': 'fwe',
    'フォ': 'fwo',
    'フャ': 'fya',
    'フュ': 'fyu',
    'フョ': 'fyo',
    'バ': 'ba',
    'ビ': 'bi',
    'ブ': 'bu',
    'ベ': 'be',
    'ボ': 'bo',
    'ビャ': 'bya',
    'ビィ': 'byi',
    'ビュ': 'byu',
    'ビェ': 'bye',
    'ビョ': 'byo',
    'パ': 'pa',
    'ピ': 'pi',
    'プ': 'pu',
    'ペ': 'pe',
    'ポ': 'po',
    'ピャ': 'pya',
    'ピィ': 'pyi',
    'ピュ': 'pyu',
    'ピェ': 'pye',
    'ピョ': 'pyo',
    'ヴァ': 'va',
    'ヴィ': 'vi',
    'ヴ': 'vu',
    'ヴェ': 've',
    'ヴォ': 'vo',
    'ヴャ': 'vya',
    'ヴュ': 'vyu',
    'ヴョ': 'vyo',
    'マ': 'ma',
    'ミ': 'mi',
    'ム': 'mu',
    'メ': 'me',
    'モ': 'mo',
    'ミャ': 'mya',
    'ミィ': 'myi',
    'ミュ': 'myu',
    'ミェ': 'mye',
    'ミョ': 'myo',
    'ヤ': 'ya',
    'ユ': 'yu',
    'ヨ': 'yo',
    'ャ': 'xya',
    'ュ': 'xyu',
    'ョ': 'xyo',
    'ラ': 'ra',
    'リ': 'ri',
    'ル': 'ru',
    'レ': 're',
    'ロ': 'ro',
    'リャ': 'rya',
    'リィ': 'ryi',
    'リュ': 'ryu',
    'リェ': 'rye',
    'リョ': 'ryo',
    'ワ': 'wa',
    'ヲ': 'wo',
    'ン': 'n',
    'ヮ': 'xwa',
}

import glob

def kana_to_romaji(kana):
    i = 0
    out = ''
    while True:
        segment = kana[i:i+2]
        if segment == '':
            break
        if segment in kanamap:
            out += kanamap[segment]
            i += 2
            continue
        segment = kana[i:i+1]
        if segment == '':
            break
        if segment in kanamap:
            out += kanamap[segment]
            i += 1
            continue
        i += 1
    return out

alphatable = {}

if __name__ == '__main__':
    for filename in glob.glob('KWDLC/knp/*/*'):
        with open(filename) as f:
            for line in f:
                if not (line == 'EOS\n' or line[0] == '#' or line[0] == '+' or line[0] == '*'):
                    kana = line.split(' ')[1]
                    for c in kana_to_romaji(kana):
                        if not c in alphatable:
                            alphatable[c] = 0
                        alphatable[c] += 1
    
    out_list = sorted(list(alphatable.items()), key=lambda x: -x[1])
    out_chars = ''.join(list(map(lambda x: x[0], out_list)))
    
    print(out_list)
    print(out_chars)